### ISSUE TITLE
docker trust info: pretty print output in table rows

### ISSUE THREAD

**Issue by riyazdf** [riyazdf/cli#6]
Must be done for:

- [x] signature info (header: `SIGNED TAGS`, `DIGEST`, `SIGNERS`)
- [x] signer / key info (header: `SIGNER`, `KEYS`)

**Comment by ashfall** [comment]
From https://github.com/riyazdf/cli/pull/11#issuecomment-318773113
>  we can shorten the key IDs to the first few chars.

**Comment by riyazdf** [comment]
We might be able to reuse the [`Trunc`](https://github.com/docker/cli/blob/6686ada6a4cf4e872af4d9bf3f61c387be934d87/cli/command/formatter/formatter.go#L42) field in the `formatter` package.  I'm using that package right now for trying pretty printing.
